Handle update
nipy/niwidgets pull request #2
Opened 2017-09-21 21:30 UTC by elyb01

Added ciftitools.py collection of functions for increased cifti support, developed at NeuroHackWeek 2017. Functions include:

cread: simplified loading of cifti files
csave: simplified saving of cifti files
clthresh: zero data below threshold
cuthresh: zero data above threshold
cmask: mask one cifti file with nonzero values from a second cifti file
cinfo: print useful cifti header metadata
cvoxels: return array of subcortical voxel coordinates
csplit: split cifti file into two gifti and one nifti file for e.g. display

These tools build on the nibabel cifti2 package.

2017-09-22 16:57 UTC, arokem commented
Just to make sure that I understand what's going on here: there seem to be (at least?) two different things happening in this PR: one is about adding the file `ciftitools.py` with support for handling cifti files (e.g., i/o, masking, thresholding, etc.) and the other is about adding volume renderings (in `niwidget_surface.py` and some additional (independent?) updates in `niwidget.py`. Is that correct?

2017-09-22 17:00 UTC, arokem commented
As a first observation, and topic for discussion, I notice that adding volume rendering adds an additional dependency on ipyvolume, and wanted to see how everyone feels about that. In particular @janfreyberg and @bs538 - what do you think about this as an additional dependency?

2017-09-24 21:13 UTC, janfreyberg commented
I'm definitely in favour of adding dependencies for things like this. Volume rendering is an important part of visualising neuroimaging data, and `ipyvolume` seems to me like a solid enough package to depend on. I like `ipyvolume` more than other solutions that open the widget outside of the notebook (eg in a new tab) - this is what a package like pycortex does right now I believe.

`ipyvolume`'s API could still change quite a bit, but I think that's fine - we'll just have to update this alongside!

As for the cifti tools - I'm not familiar with the cifti format, but don't see anything from `ciftitools.py` being imported right now - did I miss this, or are you planning to add widgets that utilise these functions, @elyb01 ?

2017-09-26 02:50 UTC, elyb01 commented
The ciftitools.py functions are independent but are needed in order to visualize cifti surfaces through showSurface.py (which I don't see in the current pull request but is another script for niwidgets developed at NeuroHackWeek, should be added soon by @melanieganz). I submitted the pull request for ciftitools.py to niwidgets per discussion with @arokem and @satra , but it could be merged elsewhere instead (e.g. nibabel), either now or down the line. I have a couple of visualization-specific functions not included in the ciftitools.py script that I'm planning to submit in a separate pull request soon.

2017-09-27 07:29 UTC, melanieganz commented
I added the pull request for the niwidgets surface visualization yesterday, so that functionality is there to look at now.

2017-10-06 08:34 UTC, janfreyberg commented
OK, the updates from @bilgelm and @melanieganz are merged now and it's looking good. It would be good if you coud pull from master so your changes to `niwidgets.py` and `niwidget_surface.py` don't override the current versions - and maybe you could rename this pull request to something more specific about `ciftitools.py`?

I do however think it would make more sense to have this in a package like nibabel, since that's specifically about reading different neuroimaging file formats.

@arokem & @matthew-brett - any thoughts on putting something to read Cifti files in nibabel?

2017-10-06 12:39 UTC, satra commented
@janfreyberg - the upcoming release of nibabel does include low level cifti2 reading and writing. 

the api that @bilgelm is proposing together with some of the things @MichielCottaar has implemented should indeed come together to create a higher level api for cifti2. but i think that requires a bit of work to get a clean api. so for the moment, perhaps the ciftitools can remain here and we move them over as part of a new PR to nibabel.

2017-10-06 13:02 UTC, bilgelm commented
Tagging @elyb01 as he was the one working on the cifti functionality.

2017-10-06 19:36 UTC, elyb01 commented
I think that's fine; agreed that NIBabel would make more sense for the cifti tools long-term. The ciftitools.py functions build partly on Michiel Cottaar's scripts, so maybe these could be merged into the planned higher-level API.

2017-10-07 08:26 UTC, janfreyberg commented on niwidgets/ciftitools.py
> +    elif isinstance(infile,str):
@elyb01 I think it would be good to also allow `pathlib.Path` objects, in addition to strings, here.

2017-10-07 08:29 UTC, janfreyberg commented on niwidgets/ciftitools.py
> +def clthresh(data,thresh,setTo=0):
the `setTo` keyword argument looks different in different places (eg. here and at line 90) - I'd be in favour of something that follows snake_case, so `set_to`.

2017-10-07 08:32 UTC, janfreyberg requested changes
@elyb01 I've since made changes to both niwidget.py and niwidget_surface.py - could you please rebase from nipy:master to avoid overriding those changes?

I've also made some minor comments below

2020-03-25 08:55 UTC, closed without merging